language: python
sudo: required
python:
  - "3.6"
# command to install dependencies
before_install:
  # install gdal
  - sudo bash install_gdal.sh
  - cp ./cfg/your_config_file.cfg ./cfg/config.cfg
install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest
