# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/
#
branches:
  except:
    - docs

dist: bionic
addons:
  apt:
    sources:
      - ppa:ubuntugis/ppa
    update: true
    packages:
      - gdal-bin
      - python-gdal
      - python3-gdal
      - libgdal-dev

language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true

services:
  - docker

before_install:
  - echo "$SERVICE_ACCOUNT_KEY" > mapswipe_workers/serviceAccountKey.json
  - echo "MOCK_SERVICE_ACCOUNT_KEY" > postgres/serviceAccountKey.json

install:
  - pip install --upgrade pip setuptools
  - pip install flake8 black

script:
  - docker-compose up --build --detach firebase_deploy
  - docker-compose run --detach postgres postgres
  - docker-compose run mapswipe_workers python -m unittest tests/integration/test_gdal.py
  # - docker-compose run mapswipe_workers python -m unittest discover --verbose --start-directory tests/integration/
  # - TODO: Run black and flake8

# before_deploy:
#   # SSH setup to deploy to server after build.
#   - apk add openssh-client
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - eval "$(ssh-agent -s)"
#   - export KEY_FILE=~/.ssh/api_server_ssh_key
#   - echo "$DEPLOYMENT_SERVER_PRIVATE_KEY" | tr -d '\r' > $KEY_FILE
#   - chmod 600 $KEY_FILE
#   - ssh-add $KEY_FILE > /dev/null
#   - ssh-keyscan -H "$DEPLOYMENT_SERVER_IP" >> ~/.ssh/known_hosts
#   - chmod 644 ~/.ssh/known_hosts
#   - ssh -i $KEY_FILE -o StrictHostKeyChecking=no "mapswipe@$DEPLOYMENT_SERVER_IP"

# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: dev

