# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/
#
dist: bionic
language: python
python:
  - "3.6"
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_444bb228fd3f_key -iv $encrypted_444bb228fd3f_iv -in .ci-mapswipe-firebase-adminsdk-80fzw-21ddcd1649.json.enc -out mapswipe_workers/serviceAccountKey.json -d

  # Create a mock file for wal-g setup
  - touch postgres/serviceAccountKey.json

install:
  - pip install --upgrade pip setuptools
  - pip install black==19.10b0 flake8==3.8.3 isort==5.5.2

script:
  - black --check mapswipe_workers
  - flake8 --count --config mapswipe_workers/setup.cfg mapswipe_workers
  - isort --check --settings-file mapswipe_workers/setup.cfg mapswipe_workers
  - docker-compose up --build --detach firebase_deploy
  - docker-compose up --build --detach postgres
  - docker-compose run mapswipe_workers python -m unittest discover --verbose --start-directory tests/unittests/
  - docker-compose run mapswipe_workers python -m unittest discover --verbose --start-directory tests/integration/

# before_deploy:
#   # SSH setup to deploy to server after build.
#   - apk add openssh-client
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - eval "$(ssh-agent -s)"
#   - export KEY_FILE=~/.ssh/api_server_ssh_key
#   - echo "$DEPLOYMENT_SERVER_PRIVATE_KEY" | tr -d '\r' > $KEY_FILE
#   - chmod 600 $KEY_FILE
#   - ssh-add $KEY_FILE > /dev/null
#   - ssh-keyscan -H "$DEPLOYMENT_SERVER_IP" >> ~/.ssh/known_hosts
#   - chmod 644 ~/.ssh/known_hosts
#   - ssh -i $KEY_FILE -o StrictHostKeyChecking=no "mapswipe@$DEPLOYMENT_SERVER_IP"

# deploy:
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     branch: dev
