# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# env:
#   global:
#     - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
#     - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
#     - GDALINST=$HOME/gdalinstall
#     - GDALBUILD=$HOME/gdalbuild
#     - PROJINST=$HOME/gdalinstall
#     - PROJBUILD=$HOME/projbuild

# jobs:
#   include:
#     - python: "3.6"
#       env:
#         GDALVERSION="3.0.4"
#         PROJVERSION="6.2.1"

# # TODO: enable this again at later stage
# addons:
#   apt:
#     packages:
#     - libhdf5-serial-dev
#     - libgdal-dev
#     - libatlas-dev
#     - libatlas-base-dev
#     - gfortran

before_install:
  - sudo apt-get update
  - sudo apt install gdal-bin python-gdal python3-gdal
  - pip install --upgrade pip setuptools
  - pip install flake8 black
  - mkdir -p ~/.config/mapswipe_workers
  - mkdir -p ~/.local/share/mapswipe_workers
  - echo "$SERVICE_ACCOUNT_KEY" > ~/.config/mapswipe_workers/serviceAccountKey.json

install:
  - pip install mapswipe_workers/
  # - docker build -t mapswipe_postgres -f ./postgres/Dockerfile-dev ./postgres

# before_script:
#   - docker run -d -p 5432:5432 --name mapswipe_postgres -e POSTGRES_DB="$POSTGRES_DB" -e POSTGRES_USER="$POSTGRES_USER" -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" mapswipe_postgres
#   - docker ps -a

script:
  # for now only test if gdal is installed
  - python -m unittest -v tests.integration_tests.test_gdal
  # TODO: Use line below once tests have been implemented
  #- python -m unittest discover -v -s mapswipe_workers/tests/integration_tests/ -p 'test_*.py'
