version: '3'
services:

    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: docker/postgres_Dockerfile
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
        ports:
            - '5432:5432'
        restart: unless-stopped
        networks:
            - mapswipe_network

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx_Dockerfile
        volumes:
            - /var/lib/mapswipe_workers/api-data/:/usr/share/nginx/html/mapswipe-api/:ro
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped
        networks:
            - mapswipe_network

    mapswipe_workers:
        container_name: mapwipe_workers
        build:
            context: .
            dockerfile: docker/mapswipe_workers_Dockerfile
        command: mapswipe_workers run --schedule h
        volumes:
            - '/var/lib/mapswipe_workers/api-data/:/var/lib/mapswipe_workers/api-data/:rw'
        restart: unless-stopped
        depends_on:
            - postgres
        networks:
            - mapswipe_network

networks:
    mapswipe_network:
        driver: bridge
        ipam:
            config: [{subnet: 172.20.0.0/16}]
