version: "2"
services:
  mapswipe-workers:
    build:
        context: ../.
        dockerfile: ./docker/Dockerfile
    volumes:
      # Copy complete folder.
      - .././:/home/mapswipe-workers/:rw
    # FIXME - Add working test command.
    # command: "cd /home/mapswipe-workers/; make tests"
