version: '3'
networks:
    mapswipe_network:
        driver: bridge
        ipam:
            config: [{subnet: 172.20.0.0/16}]
    api:
    manager_dashboard:
    mapswipe_workers:
    postgres:

volumes:
    api-data:
    letsencrypt:

services:
    nginx:
        container_name: nginx
        build:
            context: nginx/
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        ports:
            - '80:80'
            - '443:443'
        restart: unless-stopped
        networks:
            - mapswipe_network
            - api
            - manager_dashboard

    api:
        container_name: api
        build:
            context: api/
        volumes:
            - api-data:/usr/share/nginx/html/api/:ro
        expose:
            - "80"
        restart: unless-stopped
        networks:
            - api

    manager_dashboard:
        container_name: manager_dashboard
        build:
            context: manager_dashboard/
        expose:
            - "80"
        restart: unless-stopped
        networks:
            - manager_dashboard

    mapswipe_workers:
        container_name: mapwipe_workers
        build:
            context: mapswipe_workers/
        command: mapswipe_workers run --schedule h
        volumes:
            - api-data:/var/lib/mapswipe_workers/api-data/:rw
        restart: unless-stopped
        networks:
            - mapswipe_workers
            - postgres

    postgres:
        container_name: postgres
        build:
            context: postgres/
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
        expose:
            - "5432"
        restart: unless-stopped
        networks:
            - postgres
