version: "3"
services:
  # You need this only if you want to set up the psql database locally
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres_Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - mapswipe_workers_network
  # the webserver provides simple access to mapswipe data (in ./data folder)
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx_Dockerfile
    volumes:
      - ./data/:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - mapswipe_workers_network
  # MapSwipe workers split into 4 processes: import, update, transfer_results, export
  import:
    container_name: import
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=import", "--output=./data/", "--sleep_time=120", "--max_iterations=2"]
    volumes:
      - ./cfg/:/python-mapswipe-workers/cfg/:rw
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - postgres
    networks:
      - mapswipe_workers_network
  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=update", "--filter=active", "--output=./data/", "--sleep_time=180", "--max_iterations=3"]
    volumes:
      - ./cfg/:/python-mapswipe-workers/cfg/:rw
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - postgres
    networks:
      - mapswipe_workers_network
  transfer_results:
    container_name: transfer_results
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=transfer_results", "--sleep_time=60", "--max_iterations=3"]
    volumes:
      - ./cfg/:/python-mapswipe-workers/cfg/:rw
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - postgres
    networks:
      - mapswipe_workers_network
  export:
    container_name: export
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=export", "--filter=active", "--output=./data/", "--sleep_time=60", "--max_iterations=3"]
    volumes:
      - ./cfg/:/python-mapswipe-workers/cfg/:rw
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - postgres
    networks:
      - mapswipe_workers_network

networks:
  mapswipe_workers_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16

