version: "3"
services:
  import:
    container_name: import
    build:
      context: ./Dockerfile
      args:
        modus: development
        process: import
        filter: false
        list: false
        output: ./data/
        sleep_time: 60
        max_iterations: 2
    volumes:
      - ./data/:/home/mapswipe-workers/data/:rw
      - ./logs/:/home/mapswipe-workers/data/:rw
  update:
    container_name: update
    build:
      context: ./Dockerfile
      args:
        modus: development
        process: update
        filter: active
        list: false
        output: ./data/
        sleep_time: 120
        max_iterations: 2
    volumes:
      - ./data/:/home/mapswipe-workers/data/:rw
      - ./logs/:/home/mapswipe-workers/data/:rw
