version: "3"
services:
  dev-postgres:
    container_name: dev-postgres
    build:
      context: .
      dockerfile: postgres_Dockerfile
    volumes:
      - /data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - mapswipe_workers_network
  import:
    container_name: import
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=import", "--output=./data/", "--sleep_time=120", "--max_iterations=2"]
    volumes:
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - dev-postgres
    networks:
      - mapswipe_workers_network
  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=update", "--filter=active", "--output=./data/", "--sleep_time=180", "--max_iterations=3"]
    volumes:
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
    depends_on:
      - dev-postgres
    networks:
      - mapswipe_workers_network

networks:
  mapswipe_workers_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1



