version: "3"
services:
  import:
    container_name: import
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=import", "--output=./data/", "--sleep_time=120", "--max_iterations=2"]
    volumes:
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "run_mapswipe_worker.py", "--modus=development", "--process=update", "--filter=active", ""--output=./data/", "--sleep_time=180", "--max_iterations=3"]
    volumes:
      - ./data/:/python-mapswipe-workers/data/:rw
      - ./logs/:/python-mapswipe-workers/logs/:rw
