---
- name: Deploy MapSwipe Backend
  hosts: development

  tasks:
    - name: Fetch latest code base from GitHub.
      git:
        repo: 'https://github.com/mapswipe/python-mapswipe-workers.git'
        dest: $HOME/python-mapswipe-workers
        version: dev
    - name: Rebuild Docker container.
      command: docker-compose build postgres firebase_deploy mapswipe_workers_creation mapswipe_workers_stats manager_dashboard nginx api
      args:
        chdir: $HOME/python-mapswipe-workers
    - name: Restart Docker container.
      command: docker-compose up -d --force-recreate postgres firebase_deploy mapswipe_workers_creation mapswipe_workers_stats manager_dashboard nginx api
      args:
        chdir: $HOME/python-mapswipe-workers
